Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,10 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Login to GitHub Container Registry
+    - name: Create .env.prod file
+      run: echo "${{ secrets.ENV_PROD_CONTENTS }}" > .env.prod
+        
+    - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
           username: ${{ secrets.DOCKER_USERNAME }}
@@ -40,7 +43,12 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           script: |
             cd /srv/backend/
-            docker stop backend-image
-            docker rm backend-image
-            docker pull platformht/backend-image:latest
-            docker-compose up -d
+            docker-compose pull backend-image:latest
+            docker-compose up -d --no-deps backend-image:latest
+            if [ $? -eq 0 ]; then
+              echo "Deployment successful"
+              docker image prune -f
+            else
+              echo "Deployment failed"
+              exit 1
+            fi
